### ISSUE TITLE
highlighter 0.6.5 not compatible with thunderbird 60.2.1

### ISSUE THREAD

**Issue by SashaL2B** [arodier/Highlighter#9]
Please provide a solution to the above.

**Comment by bmaupin** [comment]
I've submitted a PR (#10) that fixes this. In the meantime, I packaged a new version you can install manually. Just download and install the .xpi file from here:

https://github.com/bmaupin/Highlighter/releases

**Comment by rogerlyons** [comment]
Follow up from e-mail. Have installed update, works well, thanks.

**Comment by vladr** [comment]
@bmaupin Simply upping `<em:maxVersion/>` did not work with my Thunderbird 60.2.1 installation.  I also had to get rid of closures per last bullet of [Thunderbird/Add-ons Guide 57: Removed and changed in mozilla60](https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57).  May want to apply that in your pull request as well.

[Highlighter-no-closures.patch.txt](https://github.com/arodier/Highlighter/files/2531633/Highlighter-no-closures.patch.txt)
